### ISSUE TITLE
These erros arise when i evalute my model, can u give me any suugestions?

### ISSUE THREAD

**Issue by amssljc** [MAGICS-LAB/DNABERT_S#12]
The error seems not break my code running, but it disrupt me to read results.

```
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7f01e5cb8940>
Traceback (most recent call last):
  File "/XX/software/anaconda3/envs/DNABERT_S/lib/python3.9/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/XX/software/anaconda3/envs/DNABERT_S/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/XX/software/anaconda3/envs/DNABERT_S/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/XX/software/anaconda3/envs/DNABERT_S/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7f01e5cb8940>
Traceback (most recent call last):
  File "/XX/software/anaconda3/envs/DNABERT_S/lib/python3.9/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/XX/software/anaconda3/envs/DNABERT_S/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/XX/software/anaconda3/envs/DNABERT_S/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/XX/software/anaconda3/envs/DNABERT_S/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7f01e5cb8940>
Traceback (most recent call last):
  File "/XX/software/anaconda3/envs/DNABERT_S/lib/python3.9/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/XX/software/anaconda3/envs/DNABERT_S/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/XX/software/anaconda3/envs/DNABERT_S/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/XX/software/anaconda3/envs/DNABERT_S/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by Zhihan1996** [comment]
What are the comments you were running when encountering this issue?

**Comment by amssljc** [comment]
> What are the comments you were running when encountering this issue?

Thanks for your reply! Solved it by using the following command:
```
pip install --upgrade threadpoolctl
```

**Comment by amssljc** [comment]
It worked with `threadpoolctl-3.5.0`

**Comment by Zhihan1996** [comment]
Cool. Thanks for sharing your solution.
